# Global LLM configuration
[llm] #OLLAMA:
api_type = 'ollama'
model = "qwen2.5" # model needs to support tool use
base_url = "http://localhost:11434/v1"
max_tokens = 4096
temperature = 0.0
api_key = "ollama"

# Sandbox configuration
[sandbox]
use_sandbox = false
image = "python:3.10-slim"
work_dir = "/workspace"
memory_limit = "1g"  # 512m
cpu_limit = 2.0
timeout = 300
network_enabled = false

# [llm]
# model = "claude-3-5-sonnet"
# base_url = "https://api.openai.com/v1"
# api_key = "sk-..."
# max_tokens = 4096
# temperature = 0.0

# [llm] #AZURE OPENAI:
# api_type= 'azure'
# model = "YOUR_MODEL_NAME" #"gpt-4o-mini"
# base_url = "{YOUR_AZURE_ENDPOINT.rstrip('/')}/openai/deployments/{AZURE_DEPOLYMENT_ID}"  
# api_key = "AZURE API KEY"
# max_tokens = 8096
# temperature = 0.0
# api_version="AZURE API VERSION" #"2024-08-01-preview"

# Optional configuration for specific LLM models
# [llm.vision]
# model = "claude-3-5-sonnet"
# base_url = "https://api.openai.com/v1"
# api_key = "sk-..."

[llm.vision] #OLLAMA VISION:
api_type = 'ollama'
model = "llava" # or any other multimodal model you have in Ollama that supports vision
base_url = "http://localhost:11434/v1"
max_tokens = 4096
temperature = 0.0
api_key = "ollama"